
GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/localhost:3000/subscribers/5e29ca42f286a64658a2b24d


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Nick",
    "subscribedToChannel": "CareerDevs CS-21"
}

###

DELETE http://localhost:3000/subscribers/5e29b1245dcf254084b055c3

###

PATCH http://localhost:3000/subscribers/5e28e4732460c23348c1e140
Content-Type: application/json

{
    "name": "New Name"
    
}



